### ISSUE TITLE
fixed footer covers search

### ISSUE THREAD

**Issue by johan-st** [johan-st/strandersson.se#1]
Footer is fixed at bottom and covers part of search results

**Comment by ashishpetwal** [comment]
Hi Johan, I would like to work on this issue!

**Comment by johan-st** [comment]
Thank you for your reply.
Very quick response.
Do you have a bot for finding issues?

This issue is already resolved in my local environment. Will be pushed
later today.

What kind of issues are you interested in?

**Comment by ashishpetwal** [comment]
No John, I don't have bot to find issues :)
BTW, I am interested in kind of frontend issues

**Comment by johan-st** [comment]
Great!

You're just very quick then 😊

This particular issue is fixed. Feel free to send me a message if you see
an issue you want to look at in the future.

Best regards,
Johan

**Comment by ashishpetwal** [comment]
Definitely! Thanks for considering

**Comment by johan-st** [comment]
was fixed on feb 15
